{
 "title": "Local Minikube Cluster Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(node_cpu_seconds_total,instance)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {}
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {}
   },
   { "name": "search_string", "label": "Search String" }
  ]
 },
 "panels": [
  {
   "title": "Worker Nodes Availability in Cluster",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (kube_node_status_condition{condition=\"Ready\", status=~\"true|false\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Disk Usage per Node",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (\n    sum(node_filesystem_avail_bytes{fstype!~\"tmpfs|overlay\", instance=~\"$instance\"})\n    /\n    sum(node_filesystem_size_bytes{fstype!~\"tmpfs|overlay\", instance=~\"$instance\"})\n)) * 100\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average CPU Utilization Per Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\", instance=~\"$instance\"}[5m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Bandwith Per Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "sum by (instance) (\n  rate(node_network_receive_bytes_total{device!~\"lo\", instance=~\"$instance\"}[5m])\n) / 1024",
     "legendFormat": "{{instance}}/Received"
    },
    {
     "expr": "sum by (instance) (\n  rate(node_network_transmit_bytes_total{device!~\"lo\", instance=~\"$instance\"}[5m])\n) / 1024\n",
     "legendFormat": "{{instance}}/Transmitted"
    }
   ]
  },
  {
   "title": "Memory Usage Per Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - (\n    node_memory_MemAvailable_bytes{instance=~\"$instance\"} \n    / \n    node_memory_MemTotal_bytes{instance=~\"$instance\"}\n)) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cluster Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{namespace=\"$namespace\", pod=~\"$pod\"} |= `$search_string`"
    }
   ]
  }
 ]
}